### ISSUE TITLE
Query - refreshing the secret config

### ISSUE THREAD

**Issue by vjaitly** [nearform/fastify-secrets-core#170]
I am using the secrets manager to store customer secrets - unlike the regular usage of storing the DB connection parameters or such parameters that are used during startup time.

In this scenario, the secret list can change ( it would not work for the fastify-secrets-env plugin obviously). Is there a way I can ask the plugin to refresh the secret list - or pass an update 'secrets' parameter so that it can be fetched again ?

**Comment by simoneb** [comment]
The current implementation doesn't support refreshing secrets, but we could consider decorating the fastify instance with the client, so the secrets can be retrieved on demand perhaps. I would somewhat defeat the original idea of this plugin and the original API, but it would work. What do you think @vjaitly ?

**Comment by paolochiodi** [comment]
When this was originally created there were some discussions about re-loading secrets. In the end we decided it was out of scope, but my thinking was along the line of providing a method to force reload of the secrets and triggering an event when secrets are reloaded, so that other parts of the code depending on it can also be rotated.

An alternative take would be to not pass a map of secrets, but an object with a get method that fetches the secret from the original source and caches it. This would open up options to set specific cache strategies or an attribute to force cache invalidation.

However, I think the OP use case is a bit outside the current scope of the library and none of the above would really solve because, if I understand it correctly, the list of secrets is dynamic and likely to change during the application lifecycle.
In that use case the best solution is probably to just expose the client. 
We can discuss if it's best to just expose the client as is, or wrap it so that we can add additional feature on top (i.e. caching etc)

**Comment by simoneb** [comment]
Excellent analysis Paolo, let's hear @vjaitly 's thoughts and decide what to do next

**Comment by vjaitly** [comment]
Thanks @paolochiodi for the detailed analysis. You are right in your assessment that my use case  is a little different from what this library was designed for.
The use case  for us is that the secrets list will change one the application lifecycle, and realistically speaking this can be implemented only in non env type of client ( like in my case, we are using aws ). 
However, I really like the way this library has abstracted out the  secrets manager piece from the actual implementation, and would still like to use it. Exposing the client directly as you suggested could be a good first implementation, without breaking any other feature for which the library was intended for.

The way I have used this library, I do get a list of secrets to be fetched from another part of my application, which I then pass on to the library to manage. So even the first approach of being able to force a reload with a new map could work for us. 
This could be generic feature useful for other use cases too. 
Let me know your thoughts. The caveat being that fastify-secrets-env could still not be used without doing a restart.

**Comment by paolochiodi** [comment]
I think the best approach would be to first expose a client "wrapper" so that uses can use it to re-fetch single secrets.
This would cover the use case of @vjaitly and dynamic secrets in general.
After that we can consider adding the "reload secret" functionality.

In both case the change would involve only this package and should not require any change to the depending libraries.

**Comment by simoneb** [comment]
@paolochiodi @vjaitly ok let's go with exposing a client wrapper to manually fetch the secrets for now then. @rp4rk is working on this
